version: '2'

services:
    iaccounts-webserver-1:
      hostname: iaccounts-webserver-1
      image: iaccounts-webserver
      networks:
       - frontend 
      expose:
      - 8443
      ports:
      - "8443:8443"
    iaccounts-testserver-1:
      hostname: iaccounts-testserver-1
      image: iaccounts-testserver 
      networks:
       - frontend
    iaccounts-cassandra-1:
      hostname: iaccounts-cassandra-1
      image: cassandra:latest
      networks:
        - frontend 
      command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
      expose:
        - 7000
        - 7001
        - 7199
        - 9042
        - 9160
      # volumes: # uncomment if you desire mounts, also uncomment cluster.sh
      #   - ./data/cassandra-1:/var/lib/cassandra:rw
  
networks:
  frontend:
    # Use a custom driver
    driver: bridge 
