version: '2'

services:
    iaccounts-web-entry:
      hostname: iaccounts-web-entry
      image: iaccounts-webentry 
      networks:
       - frontend
      expose:
      - 443
    iaccounts-test-server-1:
      hostname: iaccounts-test-server-1
      image: ubuntu
      networks:
       - frontend
      expose:
      - 8082
    iaccounts-webserver-1:
      hostname: iaccounts-webserver-1
      image: iaccounts-webserver
      networks:
       - frontend 
      expose:
      - 8444
    iaccounts-webserver-2:
      hostname: iaccounts-webserver-2
      image: iaccounts-webserver
      networks:
      - frontend
      expose:
      - 8445
    iaccounts-webserver-3:
      hostname: iaccounts-webserver-3
      image: iaccounts-webserver
      networks:
      - frontend
      expose:
      - 8446
    iaccounts-webserver-4:
      hostname: iaccounts-webserver-4
      image: iaccounts-webserver
      networks:
      - frontend
      expose:
      - 8447

    iaccounts-cassandra-1:
      hostname: iaccounts-cassandra-1
      image: iaccounts-cassandra
      networks:
        - frontend 
      command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
      expose:
        - 7000
        - 7001
        - 7199
        - 9042
        - 9160
      # volumes: # uncomment if you desire mounts, also uncomment cluster.sh
      #   - ./data/cassandra-1:/var/lib/cassandra:rw

    iaccounts-cassandra-2:
      hostname: iaccounts-cassandra-2
      image: iaccounts-cassandra
      networks:
        - frontend
      command: /bin/bash -c "sleep 20 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
      environment:
        - CASSANDRA_SEEDS=iaccounts-cassandra-1
      links:
        - iaccounts-cassandra-1:iaccounts-cassandra-1
      expose:
        - 7000
        - 7001
        - 7199
        - 9042
        - 9160
      # volumes: # uncomment if you desire mounts, also uncomment cluster.sh
      #   - ./data/cassandra-2:/var/lib/cassandra:rw
    iaccounts-cassandra-3:
      hostname: iaccounts-cassandra-3
      image: iaccounts-cassandra
      networks:
        - frontend
      command: /bin/bash -c "sleep 20 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
      environment:
        - CASSANDRA_SEEDS=iaccounts-cassandra-1
      links:
        - iaccounts-cassandra-1:iaccounts-cassandra-1
      expose:
        - 7000
        - 7001
        - 7199
        - 9042
        - 9160
      # volumes: # uncomment if you desire mounts, also uncomment cluster.sh
      #   - ./data/cassandra-2:/var/lib/cassandra:rw
      
  
networks:
  frontend:
    # Use a custom driver
    driver: bridge 
